# [텐서(Tensor)](https://tutorials.pytorch.kr/beginner/basics/tensorqs_tutorial.html)

- 텐서(Tensor)는 배열(Array)이나 행렬(Matrix)과 매우 유사하고 특별화된 자료구조이다.

- PyTorch 에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode) 할 수 있다.

- 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 Numpy의 ndarray와 유사하다.

- 실제로 텐서와 Numpy 배열은 종종 동일한 내부(underly) 메모리를 공유할 수 있어, 데이터를 복사할 필요가 없다.

- 또한, 텐서는 자동 미분(Automatic Differentiation)에 최적화되어 있다.

In [3]:
# 라이브러리 불러오기
import torch
import numpy as np

print("PyTorch Version :", torch.__version__, "\n")
print("Numpy Version :", np.__version__)

PyTorch Version : 1.10.2 

Numpy Version : 1.21.2


## 텐서(Tensor) 초기화

- 텐서는 여러가지 방법으로 초기화할 수 있다.

### 1. 데이터로부터 직접 생성하기

- 데이터로부터 직접 텐서를 생성할 수 있다.

- 데이터의 자료형(data type)은 자동으로 유추한다.

In [8]:
data = [[1, 2], [3, 4]]

# 'tensor' 함수를 사용하여 텐서 생성
x_data = torch.tensor(data)
display(x_data)

tensor([[1, 2],
        [3, 4]])

### 2. Numpy 배열로부터 생성하기

- 텐서는 Numpy 배열로 생성할 수 있다. (그 반대도 가능하다.)

In [12]:
np_array = np.array(data)

x_np = torch.from_numpy(np_array)
display(x_np)

tensor([[1, 2],
        [3, 4]])

### 3. 다른 텐서로부터 생성하기

- 명시적으로 재정의(override) 하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지한다.

- 인자로 주어지는 값이 텐서 자료형이어야 하며, 텐서 자료형이 아닌 경우에는 오류가 발생한다.

In [90]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor : \n {x_rand}")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.7065, 0.1942],
        [0.7657, 0.9805]])


In [27]:
# 텐서 자료형을 입력하지 않는 경우는 오류 발생
torch.ones_like(data)

TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not list

### 4. 무작위(random) 또는 상수(constant) 값을 사용하기

- `shape`은 텐서의 차원(dimension)을 나타내는 튜플로, 아래 함수들에서는 출력 텐서의 차원을 입력해주면 된다.

In [31]:
shape = (2, 3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor} \n")
print(f"Ones Tensor : \n {ones_tensor} \n")
print(f"Zeros Tensor : \n {zeros_tensor}")

Random Tensor : 
 tensor([[0.1949, 0.1711, 0.1165],
        [0.4305, 0.9235, 0.1772]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


---

## 텐서의 속성(Attribute)

- 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타낸다.

- `tensor.shape` : 텐서의 모양

- `tensor.dtype` : 텐서의 자료형

- `tensor.device` : 텐서의 저장 위치

In [36]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor : {tensor.shape} \n")
print(f"Datatype of tensor : {tensor.dtype} \n")
print(f"Device tensor is stored on : {tensor.device}")

Shape of tensor : torch.Size([3, 4]) 

Datatype of tensor : torch.float32 

Device tensor is stored on : cpu


---

## 텐서 연산(Operation)

- 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등 100가지 이상의 텐서 연산들은 [여기](https://pytorch.org/docs/stable/torch.html)에서 확인할 수 있다.

- 각 연산들은 GPU 에서도 실행할 수 있다.

- 기본적으로 텐서는 CPU에 생성된다.

- `.to` 메소드를 사용하면(GPU의 가용성을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있다.

- 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다.

In [41]:
# GPU가 존재하지 않음을 의미한다.
print(torch.cuda.is_available())

# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

False


### 1. Numpy 식의 표준 인덱싱과 슬라이싱

In [48]:
tensor = torch.ones(4, 4)

print("First row :", tensor[0], "\n")
print("First column :", tensor[:, 0], "\n")
print("Last column :", tensor[..., -1], "\n")

tensor[:, 1] = 0
display(tensor)

First row : tensor([1., 1., 1., 1.]) 

First column : tensor([1., 1., 1., 1.]) 

Last column : tensor([1., 1., 1., 1.]) 



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 2. 텐서 합치기

- `torch.cat`을 사용하여 **주워진 차원**에 따라 일련의 텐서를 연결할 수 있다.

- `dim` 인자에 `0`을 입력하면, 열 방향으로 텐서를 연결한다.

- `dim` 인자에 `1`을 입력하면, 행 방향으로 텐서를 연결한다.

In [77]:
# 열 방향으로 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim = 0)

print("Shape of tensor :", t1.shape, "\n")
print(t1)

Shape of tensor : torch.Size([12, 4]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [78]:
# 행 방향으로 텐서 합치기
t2 = torch.cat([tensor, tensor, tensor], dim = 1)

print("Shape of tensor :", t2.shape, "\n")
print(t2)

Shape of tensor : torch.Size([4, 12]) 

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


- cat 함수를 사용할 때, 연결하고자 하는 텐서의 모양이 완전 일치할 필요는 없다.

- 만약 열 방향으로 연결하고자 하는 경우에는 열이 일치하면 된다.

- 만약 행 방향으로 연결하고자 하는 경우에는 행이 일치하면 된다.

In [80]:
# 열 방향으로 합치기
row_tensor = torch.zeros(6, 4)

row_cat_tensor = torch.cat([tensor, row_tensor], dim = 0)
print("Shape of tensor :", row_cat_tensor.shape, "\n")
display(row_cat_tensor)

Shape of tensor : torch.Size([10, 4]) 



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [81]:
# 행 방향으로 합치기
column_tensor = torch.zeros(4, 7)

column_cat_tensor = torch.cat([tensor, column_tensor], dim = 1)
print("Shape of tensor :", column_cat_tensor.shape, "\n")
display(column_cat_tensor)

Shape of tensor : torch.Size([4, 11]) 



tensor([[1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.]])

### 3. 산술 연산(Arithmetic operations)

In [94]:
# 두 텐서 간의 행렬 곱을 계산한다.
# y1, y2, y3은 모두 같은 값을 갖는다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out = y3)

print(f"y1 tensor : \n {y1} \n")
print(f"y2 tensor : \n {y2} \n")
print(f"y3 tensor : \n {y3}")

y1 tensor : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y2 tensor : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y3 tensor : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


- y1과 y2 방식은 연산자를 사용하거나 tensor의 메서드를 사용하여 행렬 곱을 계산하였다.

- y3의 경우에는 먼저 tensor를 정의해주고, torch의 `matmul` 함수를 사용하여 저장 위치를 y3로 지정해주었다.

In [97]:
# 요소별 곱을 계싼한다.
# z1, z2, z3는 모두 같은 값을 갖는다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)

print(f"z1 tensor : \n {z1} \n")
print(f"z2 tensor : \n {z2} \n")
print(f"z3 tensor : \n {z3}")

z1 tensor : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z2 tensor : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z3 tensor : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 4. 단일-요소(single-element) 텐서

- 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, `item()`을 사용하여 Python 숫자 값으로 변환할 수 있다.

In [98]:
agg = tensor.sum()
agg_item = agg.item()

print(agg_item, type(agg_item))

12.0 <class 'float'>


### 5. 바꿔치기(in-place) 연산

- 연산 결과를 피연산자에 저장하는 연산을 바꿔치기 연산이라고 부르며, `_` 접미사를 갖는다.

- 예를 들어: `x.copy_(y)` 나 `x.t_()`는 `x`를 변경한다.

- `바꿔치기 연산은 메모리를 일부 절약하지만, 기록이 즉시 삭제되어 도함수 계산에 문제가 발생할 수 있다. 따라서, 사용을 권장하지 않는다.`

In [100]:
print(tensor, "\n")

tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Numpy 변환

- CPU 상의 텐서와 Numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

In [107]:
t = torch.ones(5)
print(f"t : {t} \n")

n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.]) 

n : [1. 1. 1. 1. 1.]


- 메모리 공간을 공유하고 있기 때문에, 텐서의 변경 사항이 Numpy 배열에 반영된다.

In [108]:
t.add_(1)

print(f"t : {t} \n")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.]) 

n : [2. 2. 2. 2. 2.]


### 1. Numpy 배열을 텐서로 변환하기

In [109]:
n = np.ones(5)
t = torch.from_numpy(n)

In [110]:
np.add(n, 1, out = n)

print(f"t : {t} \n")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64) 

n : [2. 2. 2. 2. 2.]
